#! /usr/local/bin/node

require.paths.push(__dirname);
require.paths.push(__dirname + '/lib');
require.paths.push(__dirname);

require('server').listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');
